server
{
        listen 443 ssl;
        listen [::]:443 ssl;

        root /var/www/wordpress/lfilloux.42.fr;

		index index.php index.html index.htm;

		server_name lfilloux.42.fr;

		ssl_protocols TLSv1.2 TLSv1.3;
    	ssl_certificate /etc/nginx/ssl/fullchain.pem;
   		ssl_certificate_key /etc/nginx/ssl/ssl_keychain.pem;

		error_log /var/log/nginx/mysite.com_error.log;
		access_log /var/log/nginx/mysite.com_access.log;

		client_max_body_size 100M;
		
		location / {
   			rewrite ^/(.*)$ /index.php?$1;
			index  index.html index.htm index.php;
		}

		location ~ .php$ {
			include snippets/fastcgi-php.conf;
			fastcgi_pass unix:/run/php/php7.4-fpm.sock;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
}