server {
	listen     443 ssl http2;
	listen [::]:443 ssl http2;
    server_name lfilloux.42.fr;
    root /var/www/html;

    ssl on;
	ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
	ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    index index.php index.htm index.html index.nginx-debian.html;

	ssl_protocols TLSv1.3;
	ssl_prefer_server_ciphers off;

    location / {
        autoindex on;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}