server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name lfilloux.42.fr;

    root /var/www;
 
    ssl_protocols TLSv1.3;
 
    ssl on;
    ssl_certificate /etc/ssl/certs/lfilloux.crt;
    ssl_certificate_key /etc/ssl/private/lfilloux.key;

    index index.php index.html index.htm;

        location /html {
                try_files $uri $uri/ =404;
    }
        location ~ \.php$ {
		fastcgi_index index.php;
	        include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}