version: '3.7'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    restart: always
    networks:
      - inception
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USR=${MYSQL_USR}
      - MYSQL_USR_PWD=${MYSQL_USR_PWD}
      - MYSQL_ROOT_USR=${MYSQL_ROOT_USR}
      - MYSQL_ROOT_PWD=${MYSQL_ROOT_PWD}
    volumes:
      - mdb_vol:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USR=${MYSQL_USR}
      - MYSQL_USR_PWD=${MYSQL_USR_PWD}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - wp_vol:/var/www/

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - 443:443
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp_vol:/var/www/

networks:
  inception:
    driver: bridge

volumes:
  mdb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lfilloux/data/mariadb
  wp_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lfilloux/data/wordpress