version: '3.8'

services:
   nginx:
    build: 
      - ./requirements/nginx
    image:
      nginx
    container_name:
      nginx
    ports: 
      - 443:443
    restart:
      always
    networks:
      - network
    environnement:
      - ./env
    depends_on:
      wordpress

networks:
  network:
    driver: bridge