version: '3'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports: 
      - 443:443
    restart: always
#    depends_on:
#      - wordpress
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mdb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lfilloux/data/mariadb
  wp_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lfilloux/data/wordpress