# !/bin/bash

cat > setup.sql << EOF
CREATE DATABASE IF NOT EXISTS '${MYSQL_DB}';
CREATE USER '${MYSQL_USR}'@'%' IDENTIFIED BY '${MYSQL_USR_PWD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DB}.* TO '${MYSQL_USR}'@'%';
FLUSH PRIVILEGES;
ALTER USER '${MYSQL_ROOT_USR}'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PWD}';
EOF