# !/bin/bash
cat > setup.sql << EOF
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER ${MYSQL_USR}@'%' IDENTIFIED BY '${MYSQL_USR_PWD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DB}.* TO ${MYSQL_USR}@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PWD}';

EOF